TRAIN_SET = [
	 [['A', 'down'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'down', 'left'], ['left']] ,
	 [['A', 'B'], ['NOOP']] ,
	 [['right'], ['B', 'left']] ,
	 [['NOOP'], ['B', 'right']] ,
	 [['B'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'B', 'right'], ['A', 'B', 'left']] ,
	 [['A', 'down', 'right'], ['down', 'left']] ,
	 [['A', 'right'], ['A']] ,
	 [['down', 'left'], ['A', 'down', 'left']] ,
	 [['A', 'B', 'right'], ['A', 'left']] ,
	 [['B', 'right'], ['A', 'down']] ,
	 [['A', 'down', 'right'], ['A', 'B', 'right']] ,
	 [['A', 'right'], ['B', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'right']] ,
	 [['A', 'left'], ['A', 'down', 'right']] ,
	 [['A', 'down', 'right'], ['right']] ,
	 [['A', 'right'], ['B']] ,
	 [['B', 'down'], ['down']] ,
	 [['A', 'down', 'right'], ['A', 'B', 'left']] ,
	 [['B', 'down', 'left'], ['B', 'left']] ,
	 [['A'], ['B', 'down']] ,
	 [['left'], ['NOOP']] ,
	 [['right'], ['NOOP']] ,
	 [['B', 'right'], ['A', 'B', 'right']] ,
	 [['A', 'B', 'down', 'left'], ['down', 'left']] ,
	 [['down', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['down', 'right'], ['B']] ,
	 [['A', 'down'], ['A']] ,
	 [['B', 'down'], ['B', 'down', 'left']] ,
	 [['right'], ['right']] ,
	 [['A', 'B', 'down', 'right'], ['down', 'left']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['A', 'right'], ['down']] ,
	 [['A', 'left'], ['right']] ,
	 [['A', 'B', 'down', 'left'], ['B', 'left']] ,
	 [['B', 'left'], ['down', 'left']] ,
	 [['A', 'left'], ['NOOP']] ,
	 [['NOOP'], ['A', 'B', 'right']] ,
	 [['A', 'right'], ['A', 'B', 'down']] ,
	 [['B', 'right'], ['A', 'B', 'left']] ,
	 [['left'], ['A', 'down']] ,
	 [['NOOP'], ['A', 'B']] ,
	 [['B', 'down'], ['A', 'B', 'left']] ,
	 [['B', 'down', 'left'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'B', 'left']] ,
	 [['down'], ['B']] ,
	 [['down', 'right'], ['NOOP']] ,
	 [['down', 'right'], ['down', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['right']] ,
	 [['right'], ['B', 'down']] ,
	 [['B', 'right'], ['B', 'right']] ,
	 [['A', 'left'], ['A', 'down']] ,
	 [['A', 'down', 'right'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['right']] ,
	 [['A', 'B', 'down'], ['B', 'down']] ,
	 [['A', 'right'], ['A', 'B', 'left']] ,
	 [['A', 'down', 'right'], ['A', 'right']] ,
	 [['A', 'down', 'right'], ['B', 'down']] ,
	 [['B', 'down'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'right'], ['A', 'right']] ,
	 [['down', 'left'], ['down', 'left']] ,
	 [['NOOP'], ['A', 'B', 'down', 'left']] ,
	 [['A', 'B'], ['B', 'right']] ,
	 [['down', 'left'], ['B', 'left']] ,
	 [['A', 'B', 'down'], ['left']] ,
	 [['A', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['left'], ['B']] ,
	 [['A', 'B', 'left'], ['down', 'left']] ,
	 [['A', 'down', 'left'], ['B']] ,
	 [['A', 'B', 'down', 'right'], ['B', 'down', 'left']] ,
	 [['down', 'left'], ['B']] ,
	 [['down'], ['A', 'B', 'down', 'left']] ,
	 [['B'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'down'], ['down', 'left']] ,
	 [['B', 'down'], ['B', 'down']] ,
	 [['B', 'down', 'right'], ['A']] ,
	 [['A', 'down', 'left'], ['down', 'left']] ,
	 [['A', 'B', 'down'], ['B']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'down', 'right']] ,
	 [['B', 'down', 'left'], ['left']] ,
	 [['down'], ['B', 'down', 'right']] ,
	 [['A', 'right'], ['B', 'down']] ,
	 [['down'], ['left']] ,
	 [['down', 'right'], ['left']] ,
	 [['A', 'B', 'left'], ['down', 'right']] ,
	 [['B'], ['A', 'B', 'right']] ,
	 [['B', 'right'], ['A', 'right']] ,
	 [['A', 'down', 'right'], ['down']] ,
	 [['A', 'left'], ['B']] ,
	 [['left'], ['A', 'B', 'right']] ,
	 [['B', 'down', 'right'], ['NOOP']] ,
	 [['down'], ['A', 'left']] ,
	 [['B', 'down', 'left'], ['A', 'down', 'left']] ,
	 [['right'], ['A']] ,
	 [['A', 'down'], ['B']] ,
	 [['A', 'B', 'down', 'left'], ['down']] ,
	 [['B', 'down', 'right'], ['A', 'B', 'left']] ,
	 [['B', 'down', 'left'], ['right']] ,
	 [['A', 'B'], ['left']] ,
	 [['left'], ['A', 'B']] ,
	 [['right'], ['A', 'right']] ,
	 [['A', 'down', 'right'], ['down', 'right']] ,
	 [['A', 'left'], ['left']] ,
	 [['A', 'B'], ['down', 'right']] ,
	 [['A', 'B', 'right'], ['down']] ,
	 [['A', 'B', 'right'], ['NOOP']] ,
	 [['A', 'B', 'right'], ['B', 'down', 'left']] ,
	 [['A', 'down'], ['left']] ,
	 [['down', 'left'], ['A', 'down']] ,
	 [['A', 'B', 'down', 'left'], ['B', 'down', 'right']] ,
	 [['B', 'down'], ['A', 'right']] ,
	 [['A', 'B', 'left'], ['A']] ,
	 [['NOOP'], ['A']] ,
	 [['A', 'B', 'down'], ['A', 'down', 'left']] ,
	 [['B'], ['down']] ,
	 [['A', 'left'], ['A', 'right']] ,
	 [['A', 'B', 'right'], ['B', 'down']] ,
	 [['down'], ['A', 'B', 'down', 'right']] ,
	 [['down'], ['down', 'left']] ,
	 [['A', 'B', 'right'], ['B', 'down', 'right']] ,
	 [['B'], ['A', 'B', 'left']] ,
	 [['A', 'right'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'down', 'left']] ,
	 [['right'], ['down']] ,
	 [['A', 'down'], ['NOOP']] ,
	 [['B', 'down'], ['NOOP']] ,
	 [['right'], ['A', 'B']] ,
	 [['down', 'right'], ['B', 'right']] ,
	 [['A', 'B', 'down', 'right'], ['B', 'left']] ,
	 [['B', 'down', 'right'], ['B', 'down']] ,
	 [['B', 'down'], ['down', 'right']] ,
	 [['B', 'down', 'right'], ['B', 'right']] ,
	 [['right'], ['A', 'left']] ,
	 [['A', 'B', 'right'], ['A', 'down', 'left']] ,
	 [['right'], ['A', 'B', 'down', 'left']] ,
	 [['NOOP'], ['A', 'B', 'left']] ,
	 [['A'], ['A', 'B', 'down']] ,
	 [['A', 'B', 'left'], ['A', 'down', 'left']] ,
	 [['down', 'right'], ['B', 'down', 'left']] ,
	 [['left'], ['right']] ,
	 [['A', 'right'], ['A', 'down']] ,
	 [['A', 'down', 'left'], ['B', 'down']] ,
	 [['B', 'down', 'left'], ['B', 'down', 'left']] ,
	 [['down', 'left'], ['A', 'B', 'right']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'left']] ,
	 [['down', 'left'], ['A', 'down', 'right']] ,
	 [['B'], ['A', 'right']] ,
	 [['down', 'left'], ['NOOP']] ,
	 [['B', 'right'], ['B', 'down']] ,
	 [['A'], ['down']] ,
	 [['down', 'right'], ['right']] ,
	 [['A', 'B', 'down'], ['down', 'right']] ,
	 [['A', 'down', 'right'], ['B', 'down', 'left']] ,
	 [['right'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'right'], ['B']] ,
	 [['down', 'left'], ['B', 'down', 'right']] ,
	 [['down', 'right'], ['down', 'right']] ,
	 [['B', 'right'], ['B']] ,
	 [['B', 'down'], ['A', 'B', 'right']] ,
	 [['A', 'B', 'down', 'left'], ['NOOP']] ,
	 [['A', 'B', 'left'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'right'], ['A', 'right']] ,
	 [['A', 'left'], ['A', 'B']] ,
	 [['A', 'down', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'down', 'left'], ['B', 'right']] ,
	 [['A', 'down', 'left'], ['down', 'right']] ,
	 [['A', 'B', 'left'], ['B', 'down', 'left']] ,
	 [['A', 'down', 'left'], ['A', 'B', 'right']] ,
	 [['A', 'down', 'right'], ['A', 'left']] ,
	 [['B'], ['B', 'right']] ,
	 [['right'], ['down', 'right']] ,
	 [['A', 'down', 'left'], ['down']] ,
	 [['B', 'left'], ['B', 'down', 'left']] ,
	 [['B', 'down', 'left'], ['A', 'B', 'right']] ,
	 [['A'], ['A', 'down']] ,
	 [['A', 'down'], ['A', 'B', 'left']] ,
	 [['A', 'B', 'left'], ['B', 'right']] ,
	 [['B', 'down', 'right'], ['A', 'B', 'down']] ,
	 [['A'], ['down', 'right']] ,
	 [['B'], ['right']] ,
	 [['A', 'down', 'left'], ['A', 'left']] ,
	 [['right'], ['A', 'down', 'right']] ,
	 [['right'], ['A', 'B', 'down']] ,
	 [['A', 'B'], ['A', 'down', 'right']] ,
	 [['NOOP'], ['down', 'left']] ,
	 [['left'], ['down', 'left']] ,
	 [['A', 'down'], ['down', 'right']] ,
	 [['A', 'B', 'down'], ['A', 'right']] ,
	 [['A', 'down', 'left'], ['right']] ,
	 [['NOOP'], ['NOOP']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'down', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['left']] ,
	 [['B', 'down', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['B', 'down', 'right'], ['A', 'down']] ,
	 [['A', 'B', 'down', 'right'], ['A']] ,
	 [['down', 'right'], ['A', 'B', 'right']] ,
	 [['A', 'B', 'right'], ['A']] ,
	 [['A', 'left'], ['A']] ,
	 [['B', 'right'], ['down']] ,
	 [['B'], ['A']] ,
	 [['A', 'down', 'left'], ['NOOP']] ,
	 [['A'], ['A', 'B', 'right']] ,
	 [['A', 'left'], ['A', 'down', 'left']] ,
	 [['B', 'right'], ['A', 'down', 'right']] ,
	 [['down'], ['A', 'B', 'right']] ,
	 [['A', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['A', 'B', 'left'], ['B', 'down']] ,
	 [['B', 'down', 'right'], ['A', 'B', 'right']] ,
	 [['A'], ['A', 'B', 'down', 'left']] ,
	 [['left'], ['down', 'right']] ,
	 [['A', 'B', 'left'], ['A', 'B', 'down']] ,
	 [['down', 'left'], ['A', 'right']] ,
	 [['A'], ['NOOP']] ,
	 [['B', 'down'], ['left']] ,
	 [['B', 'down', 'right'], ['right']] ,
	 [['down'], ['A', 'down']] ,
	 [['B', 'right'], ['B', 'down', 'right']] ,
	 [['A', 'B'], ['A', 'left']] ,
	 [['NOOP'], ['down']] ,
	 [['A', 'B', 'down', 'left'], ['B']] ,
	 [['down'], ['A', 'B']] ,
	 [['left'], ['down']] ,
	 [['A', 'B', 'left'], ['A', 'B', 'right']] ,
	 [['left'], ['B', 'down', 'left']] ,
	 [['A', 'B', 'down'], ['down']] ,
	 [['down', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['down'], ['B', 'left']] ,
	 [['B', 'down'], ['A', 'down', 'left']] ,
	 [['A', 'B'], ['B']] ,
	 [['A', 'down'], ['B', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['B', 'right']] ,
	 [['A', 'B'], ['B', 'left']] ,
	 [['B', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'B'], ['A', 'B', 'down', 'left']] ,
	 [['down'], ['A', 'B', 'left']] ,
	 [['A', 'left'], ['B', 'right']] ,
	 [['A', 'B', 'left'], ['down']] ,
	 [['A', 'down', 'left'], ['A', 'right']] ,
	 [['A', 'down', 'right'], ['A', 'down', 'left']] ,
	 [['B', 'down', 'left'], ['A', 'B']] ,
	 [['down', 'right'], ['B', 'left']] ,
	 [['A', 'left'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['A', 'right']] ,
	 [['A', 'down', 'left'], ['B', 'right']] ,
	 [['B', 'down'], ['right']] ,
	 [['B'], ['A', 'B', 'down']] ,
	 [['NOOP'], ['A', 'down', 'left']] ,
	 [['A', 'B', 'right'], ['A', 'B', 'right']] ,
	 [['A', 'right'], ['right']] ,
	 [['B', 'down', 'right'], ['B', 'down', 'right']] ,
	 [['B', 'left'], ['B', 'right']] ,
	 [['B', 'down', 'right'], ['B']] ,
	 [['B', 'left'], ['down', 'right']] ,
	 [['B', 'down'], ['A', 'B', 'down']] ,
	 [['A', 'B', 'right'], ['left']] ,
	 [['B', 'right'], ['A', 'B', 'down']] ,
	 [['A', 'B'], ['A', 'down', 'left']] ,
	 [['down'], ['down', 'right']] ,
	 [['B', 'down', 'right'], ['down']] ,
	 [['NOOP'], ['right']] ,
	 [['A', 'B', 'down', 'right'], ['NOOP']] ,
	 [['A', 'B', 'down'], ['B', 'left']] ,
	 [['A', 'down'], ['A', 'left']] ,
	 [['down'], ['A']] ,
	 [['B', 'down', 'right'], ['A', 'B']] ,
	 [['A', 'B', 'down'], ['A', 'left']] ,
	 [['A', 'down'], ['A', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['B', 'left']] ,
	 [['A', 'down', 'left'], ['A', 'down', 'right']] ,
	 [['A', 'B', 'down', 'right'], ['B', 'right']] ,
	 [['B', 'right'], ['B', 'left']] ,
	 [['B', 'left'], ['down']] ,
	 [['A', 'down'], ['B', 'down', 'left']] ,
	 [['down'], ['A', 'B', 'down']] ,
	 [['A', 'down'], ['A', 'down']] ,
	 [['B', 'right'], ['down', 'right']] ,
	 [['B', 'right'], ['A']] ,
	 [['left'], ['A', 'left']] ,
	 [['B', 'right'], ['right']] ,
	 [['A', 'left'], ['down']] ,
	 [['B', 'down'], ['B', 'down', 'right']] ,
	 [['B', 'right'], ['down', 'left']] ,
	 [['down', 'right'], ['A', 'down', 'left']] ,
	 [['A', 'right'], ['A', 'B']] ,
	 [['A', 'B'], ['B', 'down', 'right']] ,
	 [['B'], ['B']] ,
	 [['left'], ['A', 'right']] ,
	 [['NOOP'], ['left']] ,
	 [['B'], ['A', 'B', 'down', 'left']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'down', 'right']] ,
	 [['B', 'left'], ['left']] ,
	 [['A', 'down', 'right'], ['B', 'left']] ,
	 [['A', 'right'], ['A', 'left']] ,
	 [['NOOP'], ['A', 'left']] ,
	 [['down', 'right'], ['down']] ,
	 [['left'], ['A', 'B', 'down']] ,
	 [['A', 'down'], ['right']] ,
	 [['B', 'down'], ['A', 'down']] ,
	 [['B', 'down'], ['A']] ,
	 [['A', 'B'], ['A', 'B', 'left']] ,
	 [['A'], ['B']] ,
	 [['down'], ['A', 'right']] ,
	 [['A', 'B', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'down', 'right'], ['down', 'right']] ,
	 [['left'], ['left']] ,
	 [['A'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['left']] ,
	 [['B'], ['A', 'left']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'down']] ,
	 [['B', 'left'], ['A', 'left']] ,
	 [['A'], ['right']] ,
	 [['B'], ['A', 'B']] ,
	 [['A', 'B', 'down'], ['B', 'down', 'left']] ,
	 [['A', 'B', 'down', 'right'], ['down']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['right'], ['A', 'down', 'left']] ,
	 [['A', 'B'], ['A', 'B', 'down']] ,
	 [['B', 'down', 'left'], ['down', 'left']] ,
	 [['B', 'left'], ['A', 'B', 'left']] ,
	 [['down', 'left'], ['A']] ,
	 [['A', 'B'], ['down', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'down']] ,
	 [['B', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'down', 'right'], ['A', 'down', 'right']] ,
	 [['A'], ['B', 'right']] ,
	 [['down', 'left'], ['down', 'right']] ,
	 [['down', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'B', 'right'], ['A', 'down', 'right']] ,
	 [['A', 'B', 'down', 'right'], ['B']] ,
	 [['A', 'B', 'down', 'right'], ['B', 'down']] ,
	 [['A', 'down'], ['B', 'down', 'right']] ,
	 [['B', 'down', 'left'], ['A', 'B', 'left']] ,
	 [['down', 'right'], ['A', 'B']] ,
	 [['A', 'B', 'left'], ['A', 'left']] ,
	 [['B', 'down', 'right'], ['B', 'left']] ,
	 [['down'], ['B', 'down', 'left']] ,
	 [['B', 'down'], ['B', 'right']] ,
	 [['A', 'down'], ['A', 'B', 'down', 'left']] ,
	 [['down', 'right'], ['A', 'B', 'left']] ,
	 [['A'], ['left']] ,
	 [['down', 'left'], ['A', 'B']] ,
	 [['B', 'down', 'right'], ['A', 'down', 'left']] ,
	 [['A', 'B', 'left'], ['A', 'B']] ,
	 [['down'], ['A', 'down', 'right']] ,
	 [['A', 'B'], ['B', 'down']] ,
	 [['B', 'down', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'right'], ['A', 'down', 'left']] ,
	 [['NOOP'], ['B']] ,
	 [['A', 'down', 'right'], ['A', 'B', 'down']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'left']] ,
	 [['A', 'B', 'down'], ['A', 'B']] ,
	 [['right'], ['down', 'left']] ,
	 [['B', 'left'], ['right']] ,
	 [['NOOP'], ['A', 'down']] ,
	 [['B', 'left'], ['B', 'down']] ,
	 [['down', 'right'], ['A', 'down']] ,
	 [['B', 'down'], ['A', 'B']] ,
	 [['A'], ['A', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['A', 'B', 'left']] ,
	 [['A'], ['B', 'left']] ,
	 [['down', 'left'], ['A', 'B', 'left']] ,
	 [['A', 'left'], ['B', 'left']] ,
	 [['down', 'right'], ['A']] ,
	 [['A', 'right'], ['left']] ,
	 [['A'], ['A', 'B']] ,
	 [['B', 'right'], ['left']] ,
	 [['B'], ['down', 'left']] ,
	 [['A'], ['A']] ,
	 [['A', 'left'], ['A', 'B', 'right']] ,
	 [['right'], ['A', 'B', 'right']] ,
	 [['B', 'left'], ['A']] ,
	 [['right'], ['A', 'B', 'left']] ,
	 [['B', 'down'], ['B', 'left']] ,
	 [['A', 'down'], ['down', 'left']] ,
	 [['down'], ['down']] ,
	 [['B'], ['B', 'left']] ,
	 [['B', 'right'], ['NOOP']] ,
	 [['B', 'down', 'left'], ['down', 'right']] ,
	 [['A'], ['B', 'down', 'left']] ,
	 [['A', 'left'], ['down', 'left']] ,
	 [['left'], ['B', 'down']] ,
	 [['A', 'down', 'right'], ['B', 'right']] ,
	 [['down', 'left'], ['B', 'down', 'left']] ,
]

TEST_SET = [
	 [['A', 'right'], ['A', 'down', 'left']] ,
	 [['A', 'B', 'right'], ['B', 'left']] ,
	 [['A', 'left'], ['A', 'B', 'down']] ,
	 [['B', 'down', 'left'], ['B', 'down']] ,
	 [['left'], ['A', 'B', 'left']] ,
	 [['A', 'B'], ['down']] ,
	 [['A'], ['down', 'left']] ,
	 [['right'], ['B', 'down', 'left']] ,
	 [['A'], ['B', 'down', 'right']] ,
	 [['down'], ['B', 'right']] ,
	 [['A', 'B', 'right'], ['A', 'B', 'down']] ,
	 [['A', 'B'], ['A', 'B']] ,
	 [['A', 'right'], ['B', 'down', 'left']] ,
	 [['B', 'left'], ['B']] ,
	 [['down', 'right'], ['B', 'down', 'right']] ,
	 [['down', 'left'], ['B', 'right']] ,
	 [['B', 'down', 'right'], ['A', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['down', 'right']] ,
	 [['A', 'down'], ['A', 'B', 'down']] ,
	 [['down', 'right'], ['B', 'down']] ,
	 [['B', 'down'], ['A', 'B', 'down', 'left']] ,
	 [['down', 'left'], ['B', 'down']] ,
	 [['A', 'down', 'left'], ['A', 'down']] ,
	 [['A', 'B'], ['B', 'down', 'left']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'down', 'left'], ['A', 'down']] ,
	 [['A', 'B', 'left'], ['A', 'down']] ,
	 [['A', 'B', 'down'], ['A', 'B', 'down', 'left']] ,
	 [['right'], ['B', 'right']] ,
	 [['A', 'B', 'down'], ['A', 'B', 'left']] ,
	 [['B', 'down'], ['A', 'down', 'right']] ,
	 [['A', 'down', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['NOOP'], ['A', 'right']] ,
	 [['NOOP'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'down', 'right'], ['B']] ,
	 [['left'], ['A']] ,
	 [['A', 'B'], ['right']] ,
	 [['A'], ['A', 'left']] ,
	 [['A', 'left'], ['down', 'right']] ,
	 [['B', 'left'], ['A', 'B', 'right']] ,
	 [['B', 'down', 'left'], ['NOOP']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'B', 'down']] ,
	 [['A', 'left'], ['A', 'B', 'left']] ,
	 [['down', 'left'], ['A', 'left']] ,
	 [['A', 'down', 'left'], ['B', 'left']] ,
	 [['B', 'down'], ['down', 'left']] ,
	 [['left'], ['B', 'down', 'right']] ,
	 [['NOOP'], ['B', 'down', 'left']] ,
	 [['A', 'B', 'left'], ['B']] ,
	 [['A', 'B', 'right'], ['right']] ,
	 [['right'], ['B']] ,
	 [['down'], ['A', 'down', 'left']] ,
	 [['B', 'left'], ['NOOP']] ,
	 [['left'], ['B', 'right']] ,
	 [['A', 'B', 'down'], ['A', 'down']] ,
	 [['A', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['A', 'B', 'right'], ['B', 'right']] ,
	 [['B'], ['NOOP']] ,
	 [['A'], ['A', 'B', 'left']] ,
	 [['NOOP'], ['B', 'down']] ,
	 [['left'], ['A', 'down', 'left']] ,
	 [['A', 'right'], ['down', 'left']] ,
	 [['A', 'down'], ['down']] ,
	 [['A', 'B'], ['A']] ,
	 [['A', 'B', 'right'], ['down', 'left']] ,
	 [['A', 'B', 'down'], ['A', 'B', 'down']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'B']] ,
	 [['A', 'B', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'right'], ['A', 'B']] ,
	 [['B', 'right'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'right'], ['B', 'down', 'left']] ,
	 [['A', 'down', 'left'], ['B', 'down', 'left']] ,
	 [['left'], ['A', 'B', 'down', 'left']] ,
	 [['B'], ['A', 'down', 'right']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'B', 'left']] ,
	 [['A', 'down'], ['A', 'down', 'left']] ,
	 [['down', 'left'], ['A', 'B', 'down']] ,
	 [['A', 'B', 'down', 'left'], ['B', 'down']] ,
	 [['B', 'left'], ['B', 'down', 'right']] ,
	 [['NOOP'], ['B', 'left']] ,
]

VALIDATION_SET = [
	 [['A'], ['A', 'down', 'left']] ,
	 [['A', 'B'], ['A', 'down']] ,
	 [['A', 'B', 'down'], ['A']] ,
	 [['A', 'B', 'down'], ['B', 'down', 'right']] ,
	 [['A', 'B', 'down'], ['B', 'right']] ,
	 [['A', 'B', 'down'], ['NOOP']] ,
	 [['A', 'B', 'down'], ['right']] ,
	 [['A', 'B', 'down', 'left'], ['A']] ,
	 [['A', 'B', 'down', 'left'], ['A', 'B', 'right']] ,
	 [['A', 'B', 'down', 'left'], ['B', 'down', 'left']] ,
	 [['A', 'B', 'down', 'right'], ['A', 'B']] ,
	 [['A', 'B', 'down', 'right'], ['down', 'right']] ,
	 [['A', 'B', 'down', 'right'], ['left']] ,
	 [['A', 'B', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['A', 'down', 'right']] ,
	 [['A', 'B', 'left'], ['NOOP']] ,
	 [['A', 'down'], ['A', 'B']] ,
	 [['A', 'down'], ['B', 'down']] ,
	 [['A', 'down'], ['B', 'right']] ,
	 [['A', 'down', 'left'], ['A']] ,
	 [['A', 'down', 'left'], ['A', 'B']] ,
	 [['A', 'down', 'left'], ['A', 'B', 'down']] ,
	 [['A', 'down', 'left'], ['A', 'B', 'down', 'right']] ,
	 [['A', 'down', 'left'], ['A', 'B', 'left']] ,
	 [['A', 'down', 'left'], ['A', 'down', 'left']] ,
	 [['A', 'down', 'left'], ['B', 'down', 'right']] ,
	 [['A', 'down', 'right'], ['NOOP']] ,
	 [['A', 'down', 'right'], ['left']] ,
	 [['A', 'left'], ['A', 'left']] ,
	 [['A', 'left'], ['B', 'down']] ,
	 [['A', 'left'], ['B', 'down', 'left']] ,
	 [['A', 'right'], ['B', 'right']] ,
	 [['A', 'right'], ['NOOP']] ,
	 [['B'], ['A', 'down']] ,
	 [['B'], ['A', 'down', 'left']] ,
	 [['B'], ['B', 'down']] ,
	 [['B'], ['B', 'down', 'left']] ,
	 [['B'], ['down', 'right']] ,
	 [['B'], ['left']] ,
	 [['B', 'down'], ['A', 'left']] ,
	 [['B', 'down'], ['B']] ,
	 [['B', 'down', 'left'], ['A']] ,
	 [['B', 'down', 'left'], ['A', 'B', 'down']] ,
	 [['B', 'down', 'left'], ['A', 'B', 'down', 'left']] ,
	 [['B', 'down', 'left'], ['A', 'down', 'right']] ,
	 [['B', 'down', 'left'], ['A', 'left']] ,
	 [['B', 'down', 'left'], ['A', 'right']] ,
	 [['B', 'down', 'left'], ['B']] ,
	 [['B', 'down', 'left'], ['down']] ,
	 [['B', 'down', 'right'], ['B', 'down', 'left']] ,
	 [['B', 'down', 'right'], ['down', 'left']] ,
	 [['B', 'down', 'right'], ['left']] ,
	 [['B', 'left'], ['A', 'B']] ,
	 [['B', 'left'], ['A', 'B', 'down']] ,
	 [['B', 'left'], ['A', 'down']] ,
	 [['B', 'left'], ['A', 'down', 'left']] ,
	 [['B', 'left'], ['A', 'down', 'right']] ,
	 [['B', 'left'], ['A', 'right']] ,
	 [['B', 'left'], ['B', 'left']] ,
	 [['B', 'right'], ['A', 'left']] ,
	 [['NOOP'], ['A', 'B', 'down']] ,
	 [['NOOP'], ['A', 'down', 'right']] ,
	 [['NOOP'], ['B', 'down', 'right']] ,
	 [['NOOP'], ['down', 'right']] ,
	 [['down'], ['B', 'down']] ,
	 [['down'], ['NOOP']] ,
	 [['down'], ['right']] ,
	 [['down', 'left'], ['down']] ,
	 [['down', 'left'], ['left']] ,
	 [['down', 'left'], ['right']] ,
	 [['down', 'right'], ['A', 'B', 'down']] ,
	 [['down', 'right'], ['A', 'left']] ,
	 [['left'], ['A', 'B', 'down', 'right']] ,
	 [['left'], ['A', 'down', 'right']] ,
	 [['left'], ['B', 'left']] ,
	 [['right'], ['A', 'down']] ,
	 [['right'], ['left']] ,
]

TRAIN_SET_SUFFICIENT_JUMP_SET =[
    [['A', 'B', 'right'], ['A', 'B', 'right']],
	[['A', 'B', 'right'], ['A', 'B', 'down', 'right']],
	[['A', 'B'], ['A', 'down', 'right']],
	[['A', 'right'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'down'], ['A', 'down', 'right']],
	[['A', 'right'], ['A', 'down', 'right']],
	[['A', 'right'], ['A', 'right']],
	[['A', 'down', 'right'], ['A', 'B', 'down']],
	[['A', 'B', 'down', 'right'], ['A', 'down']],
	[['A', 'B', 'down', 'right'], ['A', 'B', 'down', 'right']],
	[['A', 'down', 'right'], ['A']],
	[['A', 'right'], ['A', 'B']],
	[['A', 'down', 'right'], ['A', 'B', 'right']],
	[['A', 'B'], ['A', 'B', 'down', 'right']],
	[['A', 'down', 'right'], ['A', 'B', 'down', 'right']],
	[['A'], ['A', 'down', 'right']],
	[['A', 'right'], ['A', 'down']],
	[['A'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'down', 'right']],
	[['A', 'down'], ['A', 'down', 'right']],
	[['A', 'B', 'right'], ['A', 'right']],
	[['A', 'down', 'right'], ['A', 'right']],
	[['A', 'right'], ['A']],
	[['A', 'right'], ['A', 'B', 'down']],
	[['A', 'down'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'right'], ['A', 'down']],
	[['A', 'B', 'right'], ['A', 'down', 'right']],
	[['A'], ['A', 'B', 'right']],
	[['A', 'B', 'down'], ['A', 'right']],
	[['A', 'down', 'right'], ['A', 'down']],
	[['A', 'B'], ['A', 'right']],
	[['A', 'B', 'right'], ['A']],
	[['A', 'B', 'down', 'right'], ['A']]
]

VALIDATION_SET_SUFFICIENT_JUMP_SET = [
    [['A'], ['A', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'B', 'right']],
	[['A', 'down', 'right'], ['A', 'B']],
	[['A', 'B', 'down'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'B', 'down']],
	[['A', 'B', 'down'], ['A', 'B', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'right']],
	[['A', 'down'], ['A', 'B', 'right']]
]

TEST_SET_SUFFICIENT_JUMP_SET = [
    [['A', 'B', 'right'], ['A', 'B', 'down']],
	[['A', 'B', 'down', 'right'], ['A', 'B']],
	[['A', 'right'], ['A', 'B', 'right']],
	[['A', 'B'], ['A', 'B', 'right']],
	[['A', 'down'], ['A', 'right']],
	[['A', 'down', 'right'], ['A', 'down', 'right']],
	[['A', 'B', 'right'], ['A', 'B']]
]

TRAIN_SET_SUFFICIENT_RIGHT_SET = [
    [['A', 'B', 'down', 'right'], ['B', 'right']],
	[['down', 'right'], ['A', 'down', 'right']],
	[['A', 'down', 'right'], ['B', 'right']],
	[['B', 'down', 'right'], ['A', 'right']],
	[['right'], ['A', 'B', 'right']],
	[['A', 'down', 'right'], ['A', 'B', 'right']],
	[['right'], ['A', 'down', 'right']],
	[['A', 'down', 'right'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'B', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'down', 'right']],
	[['B', 'down', 'right'], ['A', 'down', 'right']],
	[['A', 'down', 'right'], ['A', 'right']],
	[['A', 'B', 'down', 'right'], ['right']],
	[['A', 'down', 'right'], ['down', 'right']],
	[['A', 'down', 'right'], ['A', 'down', 'right']],
	[['A', 'B', 'right'], ['A', 'down', 'right']],
	[['down', 'right'], ['A', 'right']],
	[['B', 'down', 'right'], ['A', 'B', 'right']],
	[['B', 'right'], ['A', 'right']],
	[['B', 'right'], ['A', 'B', 'right']],
	[['A', 'B', 'right'], ['A', 'B', 'right']],
	[['B', 'right'], ['A', 'down', 'right']],
	[['A', 'B', 'right'], ['A', 'right']],
	[['right'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'right']],
	[['A', 'down', 'right'], ['right']],
	[['right'], ['A', 'right']],
	[['A', 'right'], ['B', 'down', 'right']],
	[['A', 'right'], ['right']],
	[['A', 'B', 'right'], ['B', 'down', 'right']],
	[['A', 'right'], ['down', 'right']],
	[['A', 'right'], ['A', 'right']]
]

VALIDATION_SET_SUFFICIENT_RIGHT_SET = [
    [['A', 'right'], ['A', 'B', 'down', 'right']],
	[['B', 'down', 'right'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'right'], ['down', 'right']],
	[['A', 'right'], ['A', 'B', 'right']],
	[['A', 'B', 'down', 'right'], ['A', 'B', 'down', 'right']],
	[['B', 'right'], ['A', 'B', 'down', 'right']],
    [['A', 'B', 'down', 'right'], ['B', 'down', 'right']]
]

TEST_SET_SUFFICIENT_RIGHT_SET = [
    [['A', 'B', 'down', 'right'], ['down', 'right']],
	[['A', 'down', 'right'], ['B', 'down', 'right']],
	[['A', 'B', 'right'], ['right']],
	[['A', 'right'], ['A', 'down', 'right']],
	[['A', 'right'], ['B', 'right']],
	[['down', 'right'], ['A', 'B', 'down', 'right']],
	[['A', 'B', 'right'], ['A', 'B', 'down', 'right']],
]
